version: '{build}'
image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release

# Use the source dir expected by gclient.
clone_folder: c:\projects\pdfium\src

# Before checkout.
init:
  - cd %APPVEYOR_BUILD_FOLDER%\..\..
  - appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z -bd x depot_tools.zip -odepot_tools
  - set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - depot_tools\update_depot_tools
  - cd %APPVEYOR_BUILD_FOLDER%

# After checkout.
install:
  - set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - PATH C:\projects\depot_tools;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - gclient config https://%APPVEYOR_REPO_PROVIDER%.com/%APPVEYOR_REPO_NAME% --unmanaged
  - gclient sync

build_script:
  - set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - cd %APPVEYOR_BUILD_FOLDER%\pdfium
  - gn gen --args="pdf_is_shared_lib=true pdf_bundle_freetype=true pdf_enable_v8=false pdf_enable_xfa=false pdf_use_skia=false use_system_zlib=false use_system_freetype=false pdf_is_standalone=true is_component_build=false is_official_build=true is_debug=false target_cpu=\"x86\"" "out/release"
  - cd out/release
  - ninja pdfium
  - 7z a pdfium.zip %APPVEYOR_BUILD_FOLDER%\pdfium\public


artifacts:
  - path: '**\pdfium.dll'
  - path: '**\pdfium.lib'
  - path: '**\pdfium.*'
  - path: '**\pdfium.zip'
